name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "=== Checking build directory structure ==="
          ls -la dist/
          echo ""
          echo "=== Checking if index.html exists ==="
          if [ -f "dist/index.html" ]; then
            echo "✓ index.html found"
            ls -la dist/index.html
          else
            echo "✗ index.html not found"
            exit 1
          fi
          echo ""
          echo "=== Checking assets directory ==="
          if [ -d "dist/assets" ]; then
            echo "✓ assets directory found"
            ls -la dist/assets/
            echo ""
            echo "=== File sizes ==="
            du -h dist/assets/*
          else
            echo "✗ assets directory not found"
          fi
          echo ""
          echo "=== Checking for config file ==="
          if [ -f "dist/staticwebapp.config.json" ]; then
            echo "✓ staticwebapp.config.json found"
            ls -la dist/staticwebapp.config.json
          else
            echo "ℹ staticwebapp.config.json not found (optional)"
          fi
          echo ""
          echo "=== Index.html script references ==="
          if [ -f "dist/index.html" ]; then
            grep -n "assets/" dist/index.html || echo "No asset references found"
          fi
      
      - name: Deleting and Uploading exiting blobs in $web contaier
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Intiating deletion of old blobs from $web..."
            az storage blob delete-batch \
              --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
              --sas-token "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --delete-snapshots include \
              --source "\$web"
            
            echo "Uploading new files to \$web container..."
            az storage blob upload-batch \
              --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
              --destination "\$web" \
              --source "dist" \
              --overwrite \
              --sas-token "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" 
        
            echo "Deployment completed successfully!"
            echo "Your website should be available at: https://${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}.z13.web.core.windows.net/"
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}